SET(SOURCES ui_Screen1.c
    ui_Screen3.c
    ui_Screen2.c
    ui_Screen4.c
    ui.c
    ui_comp_hook.c
    ui_helpers.c
    ui_events.c
    ui_img_new_piskel_png.c
    ui_img_1170035795.c
    ui_img_1251106030.c
    ui_img_419666915.c
    ui_img_912352328.c
    ui_img_1219156610.c
    ui_img_944301748.c
    ui_img_1138086375.c
    ui_img_682786516.c
    ui_img_1025371983.c
    ui_img_682781265.c
    ui_img_682784466.c
    ui_img_682783315.c
    ui_img_1630771788.c)

add_library(ui ${SOURCES})
