// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"
#include "ui_Screen3.h"
#include "ui_Screen2.h"
#include "ui_Screen4.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_new_piskel_png);    // assets/New Piskel.png
LV_IMG_DECLARE(ui_img_1170035795);    // assets/New Piskel (3).png
LV_IMG_DECLARE(ui_img_1251106030);    // assets/New Piskel (2).png
LV_IMG_DECLARE(ui_img_419666915);    // assets/New Piskel-2.png (1).png
LV_IMG_DECLARE(ui_img_912352328);    // assets/New Piskel (4).png
LV_IMG_DECLARE(ui_img_1219156610);    // assets/New Piskel (6).png
LV_IMG_DECLARE(ui_img_944301748);    // assets/New Piskel (8).png
LV_IMG_DECLARE(ui_img_1138086375);    // assets/New Piskel (7).png
LV_IMG_DECLARE(ui_img_682786516);    // assets/New Piskel (13).png
LV_IMG_DECLARE(ui_img_1025371983);    // assets/New Piskel (9).png
LV_IMG_DECLARE(ui_img_682781265);    // assets/New Piskel (10).png
LV_IMG_DECLARE(ui_img_682784466);    // assets/New Piskel (11).png
LV_IMG_DECLARE(ui_img_682783315);    // assets/New Piskel (12).png
LV_IMG_DECLARE(ui_img_1630771788);    // assets/New Piskel-2.png (2).png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
