// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Image9;
extern void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Panel3;
extern void ui_event_ImgButton2(lv_event_t * e);
extern lv_obj_t * ui_ImgButton2;
extern lv_obj_t * ui_Panel6;
extern void ui_event_ImgButton7(lv_event_t * e);
extern lv_obj_t * ui_ImgButton7;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Panel8;
extern void ui_event_ImgButton9(lv_event_t * e);
extern lv_obj_t * ui_ImgButton9;
extern lv_obj_t * ui_Image4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

