// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN4_H
#define UI_SCREEN4_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen4
extern void ui_Screen4_screen_init(void);
extern void ui_Screen4_screen_destroy(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Panel16;
extern void ui_event_ImgButton12(lv_event_t * e);
extern lv_obj_t * ui_ImgButton12;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

