// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void on_skip_next_click(lv_event_t * e)
{
	// Your code here
}

void on_play_pause_toggle(lv_event_t * e)
{
	// Your code here
}

void on_skip_prev_click(lv_event_t * e)
{
	// Your code here
}

void on_click_vol_dec(lv_event_t * e)
{
	// Your code here
}

void on_click_vol_inc(lv_event_t * e)
{
	// Your code here
}

void seek_slider_release(lv_event_t * e)
{
	// Your code here
}

void on_genre_changed(lv_event_t * e)
{
	// Your code here
}

void onartistchange(lv_event_t * e)
{
	// Your code here
}

void onalbumchange(lv_event_t * e)
{
	// Your code here
}

void random_song(lv_event_t * e)
{
	// Your code here
}
