// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void on_skip_next_click(lv_event_t * e);
void on_play_pause_toggle(lv_event_t * e);
void on_skip_prev_click(lv_event_t * e);
void on_click_vol_dec(lv_event_t * e);
void on_click_vol_inc(lv_event_t * e);
void seek_slider_release(lv_event_t * e);
void on_genre_changed(lv_event_t * e);
void onartistchange(lv_event_t * e);
void onalbumchange(lv_event_t * e);
void random_song(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
