// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Panel12;
extern void ui_event_uigenredropdown(lv_event_t * e);
extern lv_obj_t * ui_uigenredropdown;
extern void ui_event_uiartsitdropdown(lv_event_t * e);
extern lv_obj_t * ui_uiartsitdropdown;
extern void ui_event_uialbumdropdown(lv_event_t * e);
extern lv_obj_t * ui_uialbumdropdown;
extern lv_obj_t * ui_uisonglistcontainer;
extern lv_obj_t * ui_Panel13;
extern void ui_event_ImgButton3(lv_event_t * e);
extern lv_obj_t * ui_ImgButton3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

