// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_Panel12 = NULL;
lv_obj_t * ui_uigenredropdown = NULL;
lv_obj_t * ui_uiartsitdropdown = NULL;
lv_obj_t * ui_uialbumdropdown = NULL;
lv_obj_t * ui_uisonglistcontainer = NULL;
lv_obj_t * ui_Panel13 = NULL;
lv_obj_t * ui_ImgButton3 = NULL;
// event funtions
void ui_event_uigenredropdown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        on_genre_changed(e);
    }
}

void ui_event_uiartsitdropdown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        onartistchange(e);
    }
}

void ui_event_uialbumdropdown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        onalbumchange(e);
    }
}

void ui_event_ImgButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image5 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image5, &ui_img_new_piskel_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel12 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Panel12, 364);
    lv_obj_set_height(ui_Panel12, 332);
    lv_obj_set_x(ui_Panel12, -1);
    lv_obj_set_y(ui_Panel12, -4);
    lv_obj_set_align(ui_Panel12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel12, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel12, lv_color_hex(0xFFE2E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel12, lv_color_hex(0xFFE2E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uigenredropdown = lv_dropdown_create(ui_Screen3);
    lv_dropdown_set_options(ui_uigenredropdown, "Genre\nOption 2\nOption 3");
    lv_obj_set_width(ui_uigenredropdown, 107);
    lv_obj_set_height(ui_uigenredropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uigenredropdown, -116);
    lv_obj_set_y(ui_uigenredropdown, -135);
    lv_obj_set_align(ui_uigenredropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_uigenredropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_uigenredropdown, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uigenredropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_uigenredropdown, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uigenredropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_uigenredropdown, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_uigenredropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiartsitdropdown = lv_dropdown_create(ui_Screen3);
    lv_dropdown_set_options(ui_uiartsitdropdown, "Artists\nOption 2\nOption 3");
    lv_obj_set_width(ui_uiartsitdropdown, 106);
    lv_obj_set_height(ui_uiartsitdropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uiartsitdropdown, -2);
    lv_obj_set_y(ui_uiartsitdropdown, -135);
    lv_obj_set_align(ui_uiartsitdropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_uiartsitdropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_uiartsitdropdown, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiartsitdropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_uiartsitdropdown, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiartsitdropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_uiartsitdropdown, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_uiartsitdropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_uiartsitdropdown, lv_color_hex(0x808080), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiartsitdropdown, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_uiartsitdropdown), lv_color_hex(0x808080),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_uiartsitdropdown), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uialbumdropdown = lv_dropdown_create(ui_Screen3);
    lv_dropdown_set_options(ui_uialbumdropdown, "Albums\nOption 2\nOption 3");
    lv_obj_set_width(ui_uialbumdropdown, 103);
    lv_obj_set_height(ui_uialbumdropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uialbumdropdown, 108);
    lv_obj_set_y(ui_uialbumdropdown, -136);
    lv_obj_set_align(ui_uialbumdropdown, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_uialbumdropdown, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_uialbumdropdown, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_uialbumdropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_uialbumdropdown, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uialbumdropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_uialbumdropdown, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uialbumdropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_uialbumdropdown, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_uialbumdropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_uialbumdropdown, lv_color_hex(0x808080), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uialbumdropdown, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_uisonglistcontainer = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_uisonglistcontainer, 329);
    lv_obj_set_height(ui_uisonglistcontainer, 234);
    lv_obj_set_x(ui_uisonglistcontainer, -4);
    lv_obj_set_y(ui_uisonglistcontainer, 10);
    lv_obj_set_align(ui_uisonglistcontainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_uisonglistcontainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_uisonglistcontainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_scroll_dir(ui_uisonglistcontainer, LV_DIR_VER);
    lv_obj_set_style_bg_color(ui_uisonglistcontainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uisonglistcontainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_uisonglistcontainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_uisonglistcontainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_row(ui_uisonglistcontainer, 8, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_uisonglistcontainer, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Panel13 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Panel13, 68);
    lv_obj_set_height(ui_Panel13, 63);
    lv_obj_set_x(ui_Panel13, 112);
    lv_obj_set_y(ui_Panel13, 162);
    lv_obj_set_align(ui_Panel13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton3 = lv_imgbtn_create(ui_Screen3);
    lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_682786516, NULL);
    lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_682786516, NULL);
    lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_682786516, NULL);
    lv_obj_set_width(ui_ImgButton3, 63);
    lv_obj_set_height(ui_ImgButton3, 63);
    lv_obj_set_x(ui_ImgButton3, 107);
    lv_obj_set_y(ui_ImgButton3, 163);
    lv_obj_set_align(ui_ImgButton3, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_uigenredropdown, ui_event_uigenredropdown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_uiartsitdropdown, ui_event_uiartsitdropdown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_uialbumdropdown, ui_event_uialbumdropdown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton3, ui_event_ImgButton3, LV_EVENT_ALL, NULL);

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_Image5 = NULL;
    ui_Panel12 = NULL;
    ui_uigenredropdown = NULL;
    ui_uiartsitdropdown = NULL;
    ui_uialbumdropdown = NULL;
    ui_uisonglistcontainer = NULL;
    ui_Panel13 = NULL;
    ui_ImgButton3 = NULL;

}
